### ISSUE TITLE
Failed to copy file ...FindLibRaw.cmake

### ISSUE THREAD

**Issue by JerryBlack** [rlancaste/kstars-on-osx-craft#12]
started with a fresh install, I believe and I get this error on FindLibRaw.cmake

Any ideas?

executing command: /Users/jerryblack/AstroRoot/craft-root/dev-utils/bin/ninja -j 16 install
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/pkgconfig/libraw.pc
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/pkgconfig/libraw_r.pc
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_alloc.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_const.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_datastream.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_internal.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_types.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_version.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_config.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.20.0.0.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.20.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.20.0.0.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.20.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/COPYRIGHT
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/LICENSE.CDDL
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/LICENSE.LGPL
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/Changelog.txt
executing command: /usr/bin/dsymutil /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib -o /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2-dbg/lib/libraw.20.0.0.dylib.dSYM
executing command: /usr/bin/strip -x -S /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
executing command: /usr/bin/codesign -f -s - /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
executing command: /usr/bin/dsymutil /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib -o /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2-dbg/lib/libraw_r.20.0.0.dylib.dSYM
executing command: /usr/bin/strip -x -S /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
executing command: /usr/bin/codesign -f -s - /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
executing command: /usr/bin/codesign -s - -f --deep --preserve-metadata=identifier,entitlements /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib: replacing existing signature
executing command: /usr/bin/codesign -s - -f --deep --preserve-metadata=identifier,entitlements /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib: replacing existing signature
*** Action: post-install for libs/libraw ***
*** Action: qmerge for libs/libraw ***
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_alloc.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_alloc.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_version.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_version.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_const.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_const.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_internal.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_internal.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_datastream.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_datastream.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_config.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_config.h
Overriding:	/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_types.h with
		/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_types.h
Failed to create hardlink /Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake for /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
Failed to copy file:
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake to
/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
Traceback (most recent call last):
  File "/Users/jerryblack/AstroRoot/craft-root/craft/bin/utils.py", line 577, in copyFile
    shutil.copy2(src, dest, follow_symlinks=False)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake'
Action: qmerge for libs/libraw:0.20.2 FAILED
*** Craft all failed: libs/libraw after 10 seconds ***
fatal error: package libs/libraw all failed
Craft stopped with out completing ['libs/libraw', 'libs/giflib', 'libs/webp', 'libs/tiff', 'libs/liblame', 'libs/libopus', 'libs/libsamplerate', 'libs/libsdl2', 'libs/libvorbis', 'libs/libvpx', 'libs/x264', 'libs/x265', 'libs/fribidi', 'libs/libass', 'perl-modules/xml-parser', 'dev-utils/intltool', 'dev-utils/yasm', 'libs/aom', 'libs/dav1d', 'libs/zimg', 'libs/ffmpeg', 'libs/librtlsdr', 'libs/protobuf', 'libs/opencv/opencv', 'libs/indiserver-3rdparty-libraries']
jerryblack@Mac-Studio kstars-on-osx-craft % >....                                                                                                                                                                                        
-- Install configuration: "RelWithDebInfo"
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/pkgconfig/libraw.pc
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/pkgconfig/libraw_r.pc
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_alloc.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_const.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_datastream.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_internal.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_types.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_version.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_config.h
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.20.0.0.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.20.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.20.0.0.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.20.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/lib/libraw_r.dylib
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/COPYRIGHT
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/LICENSE.CDDL
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/LICENSE.LGPL
-- Installing: /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/Users/jerryblack/AstroRoot/craft-root/share/libraw/Changelog.txt
executing command: /usr/bin/dsymutil /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib -o /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2-dbg/lib/libraw.20.0.0.dylib.dSYM
executing command: /usr/bin/strip -x -S /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
executing command: /usr/bin/codesign -f -s - /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
executing command: /usr/bin/dsymutil /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib -o /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2-dbg/lib/libraw_r.20.0.0.dylib.dSYM
executing command: /usr/bin/strip -x -S /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
executing command: /usr/bin/codesign -f -s - /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
executing command: /usr/bin/codesign -s - -f --deep --preserve-metadata=identifier,entitlements /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw.20.0.0.dylib: replacing existing signature
executing command: /usr/bin/codesign -s - -f --deep --preserve-metadata=identifier,entitlements /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/lib/libraw_r.20.0.0.dylib: replacing existing signature
*** Action: post-install for libs/libraw ***
*** Action: qmerge for libs/libraw ***
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_alloc.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_alloc.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_version.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_version.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_const.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_const.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_internal.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_internal.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_datastream.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_datastream.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_config.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_config.h
Overriding:     /Users/jerryblack/AstroRoot/craft-root/include/libraw/libraw_types.h with
                /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/include/libraw/libraw_types.h
Failed to create hardlink /Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake for /Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
Failed to copy file:
/Users/jerryblack/AstroRoot/craft-root/build/libs/libraw/image-RelWithDebInfo-0.20.2/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake to
/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake
Traceback (most recent call last):
  File "/Users/jerryblack/AstroRoot/craft-root/craft/bin/utils.py", line 577, in copyFile
    shutil.copy2(src, dest, follow_symlinks=False)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/Users/jerryblack/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/FindLibRaw.cmake'
Action: qmerge for libs/libraw:0.20.2 FAILED
*** Craft all failed: libs/libraw after 10 seconds ***
fatal error: package libs/libraw all failed
Craft stopped with out completing ['libs/libraw', 'libs/giflib', 'libs/webp', 'libs/tiff', 'libs/liblame', 'libs/libopus', 'libs/libsamplerate', 'libs/libsdl2', 'libs/libvorbis', 'libs/libvpx', 'libs/x264', 'libs/x265', 'libs/fribidi', 'libs/libass', 'perl-modules/xml-parser', 'dev-utils/intltool', 'dev-utils/yasm', 'libs/aom', 'libs/dav1d', 'libs/zimg', 'libs/ffmpeg', 'libs/librtlsdr', 'libs/protobuf', 'libs/opencv/opencv', 'libs/indiserver-3rdparty-libraries']

**Comment by rlancaste** [comment]
It says this is a permission issue.  Maybe you can check what the permissions on that folder are?  Also it looks like it is using python from homebrew to complete the operation.  That is not bad in and of itself since I think craft does tend to use that, but maybe python could be updated?  Another option is that maybe we could open an issue with craft since libraw is of course one of their recipes?

**Comment by rlancaste** [comment]
Another thought is that you could try just doing libraw in craft to see what it does, you can run these commands in terminal:

 cd ~/AstroRoot/craft-root/ ; source ~/AstroRoot/craft-root/craft/craftenv.sh;
craft -vi libraw

**Comment by rlancaste** [comment]
If for some reason it works, then you can just continue the build again.

**Comment by JerryBlack** [comment]
As of yet, I haven't gotten around the file permission issue. Without knowing what I'm doing, it seems to me that the system (Ventura 13.2.1) isn't letting me change permissions within the ~/AstroRoot/craft-root/dev-utils/cmake-base/CMake.app/Contents/share/cmake-3.23/Modules/ which I'm guessing is why the script  or the libraw specific lines can't do the copy. The modules folder is drwxr-xr-x ,  but the existing files within are -rw-r--r--
